name: prompt-comp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pytorch
  - pytorch-cuda=12.1
  - transformers
  - evaluate
  - rouge-score
  - bert_score
  - sentence-transformers
  - peft
  - wandb
  - datasets
  - tqdm
  - pip
  - spacy
  - chardet
  - pip:
      - jupyterlab
      - llmlingua
